# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stepa\PycharmProjects\testtask\ui\DialogSignal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSignal(object):
    def setupUi(self, DialogSignal):
        DialogSignal.setObjectName("DialogSignal")
        DialogSignal.resize(320, 240)
        DialogSignal.setMinimumSize(QtCore.QSize(320, 240))
        DialogSignal.setMaximumSize(QtCore.QSize(320, 240))
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSignal)
        self.buttonBox.setGeometry(QtCore.QRect(10, 200, 300, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(DialogSignal)
        self.widget.setGeometry(QtCore.QRect(10, 80, 301, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.list_channels = QtWidgets.QComboBox(self.widget)
        self.list_channels.setObjectName("list_channels")
        self.horizontalLayout.addWidget(self.list_channels)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(DialogSignal)
        self.buttonBox.accepted.connect(DialogSignal.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSignal.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSignal)

    def retranslateUi(self, DialogSignal):
        _translate = QtCore.QCoreApplication.translate
        DialogSignal.setWindowTitle(_translate("DialogSignal", "Dialog"))
        self.label.setText(_translate("DialogSignal", "Номер точки"))
