# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stepa\PycharmProjects\testtask\ui\DialogSignalEnvelope.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSignalEvelope(object):
    def setupUi(self, DialogSignalEvelope):
        DialogSignalEvelope.setObjectName("DialogSignalEvelope")
        DialogSignalEvelope.resize(320, 240)
        DialogSignalEvelope.setMinimumSize(QtCore.QSize(320, 240))
        DialogSignalEvelope.setMaximumSize(QtCore.QSize(320, 240))
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSignalEvelope)
        self.buttonBox.setGeometry(QtCore.QRect(10, 200, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(DialogSignalEvelope)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 287, 77))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.frequency_min = QtWidgets.QLineEdit(self.layoutWidget)
        self.frequency_min.setObjectName("frequency_min")
        self.horizontalLayout.addWidget(self.frequency_min)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.frequency_max = QtWidgets.QLineEdit(self.layoutWidget)
        self.frequency_max.setObjectName("frequency_max")
        self.horizontalLayout_2.addWidget(self.frequency_max)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogSignalEvelope)
        self.buttonBox.accepted.connect(DialogSignalEvelope.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSignalEvelope.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSignalEvelope)

    def retranslateUi(self, DialogSignalEvelope):
        _translate = QtCore.QCoreApplication.translate
        DialogSignalEvelope.setWindowTitle(_translate("DialogSignalEvelope", "Dialog"))
        self.label.setText(_translate("DialogSignalEvelope", "Параметры полосового фильтра"))
        self.label_2.setText(_translate("DialogSignalEvelope", "Частота среза 1"))
        self.label_3.setText(_translate("DialogSignalEvelope", "Частота среза 2"))
