# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stepa\PycharmProjects\testtask\ui\DialogSignalEnvelopeSpectrum.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSignalEnvelopeSpectrum(object):
    def setupUi(self, DialogSignalEnvelopeSpectrum):
        DialogSignalEnvelopeSpectrum.setObjectName("DialogSignalEnvelopeSpectrum")
        DialogSignalEnvelopeSpectrum.resize(340, 240)
        DialogSignalEnvelopeSpectrum.setMinimumSize(QtCore.QSize(340, 240))
        DialogSignalEnvelopeSpectrum.setMaximumSize(QtCore.QSize(340, 240))
        DialogSignalEnvelopeSpectrum.setBaseSize(QtCore.QSize(0, 0))
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSignalEnvelopeSpectrum)
        self.buttonBox.setGeometry(QtCore.QRect(10, 200, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(DialogSignalEnvelopeSpectrum)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 327, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.min_spectrum_f = QtWidgets.QLineEdit(self.layoutWidget)
        self.min_spectrum_f.setObjectName("min_spectrum_f")
        self.verticalLayout_2.addWidget(self.min_spectrum_f)
        self.max_spectrum_f = QtWidgets.QLineEdit(self.layoutWidget)
        self.max_spectrum_f.setObjectName("max_spectrum_f")
        self.verticalLayout_2.addWidget(self.max_spectrum_f)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogSignalEnvelopeSpectrum)
        self.buttonBox.accepted.connect(DialogSignalEnvelopeSpectrum.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogSignalEnvelopeSpectrum.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogSignalEnvelopeSpectrum)

    def retranslateUi(self, DialogSignalEnvelopeSpectrum):
        _translate = QtCore.QCoreApplication.translate
        DialogSignalEnvelopeSpectrum.setWindowTitle(_translate("DialogSignalEnvelopeSpectrum", "Спектр огибающей"))
        self.label_4.setText(_translate("DialogSignalEnvelopeSpectrum", "Диапазон построения"))
        self.label_2.setText(_translate("DialogSignalEnvelopeSpectrum", "Минимальная частота"))
        self.label_3.setText(_translate("DialogSignalEnvelopeSpectrum", "Максимальная частота"))
